/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    courses: Course;
    cohorts: Cohort;
    lessons: Lesson;
    enrollments: Enrollment;
    progress: Progress;
    attendance: Attendance;
    assignments: Assignment;
    submissions: Submission;
    certificates: Certificate;
    posts: Post;
    categories: Category;
    testimonials: Testimonial;
    instructors: Instructor;
    contacts: Contact;
    partners: Partner;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    courses: CoursesSelect<false> | CoursesSelect<true>;
    cohorts: CohortsSelect<false> | CohortsSelect<true>;
    lessons: LessonsSelect<false> | LessonsSelect<true>;
    enrollments: EnrollmentsSelect<false> | EnrollmentsSelect<true>;
    progress: ProgressSelect<false> | ProgressSelect<true>;
    attendance: AttendanceSelect<false> | AttendanceSelect<true>;
    assignments: AssignmentsSelect<false> | AssignmentsSelect<true>;
    submissions: SubmissionsSelect<false> | SubmissionsSelect<true>;
    certificates: CertificatesSelect<false> | CertificatesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    instructors: InstructorsSelect<false> | InstructorsSelect<true>;
    contacts: ContactsSelect<false> | ContactsSelect<true>;
    partners: PartnersSelect<false> | PartnersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    navigation: Navigation;
    homepage: Homepage;
    pages: Page;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    homepage: HomepageSelect<false> | HomepageSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  phone?: string | null;
  avatar?: (number | null) | Media;
  role?: ('admin' | 'instructor' | 'student') | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  caption?: string | null;
  category?: ('instructor' | 'testimonial' | 'gallery' | 'partner' | 'logo' | 'hero' | 'other') | null;
  /**
   * לתמונות שמאוחסנות ב-Cloudinary או שרת חיצוני
   */
  externalUrl?: string | null;
  /**
   * Cloudinary Media Information
   */
  cloudinary?: {
    /**
     * Cloudinary Public ID (used for transformations)
     */
    public_id?: string | null;
    /**
     * Type of the resource (image, video, raw)
     */
    resource_type?: string | null;
    /**
     * File format
     */
    format?: string | null;
    /**
     * Secure delivery URL
     */
    secure_url?: string | null;
    /**
     * File size in bytes
     */
    bytes?: number | null;
    /**
     * Creation timestamp
     */
    created_at?: string | null;
    /**
     * Current version number
     */
    version?: string | null;
    /**
     * Unique version identifier
     */
    version_id?: string | null;
    /**
     * Width in pixels
     */
    width?: number | null;
    /**
     * Height in pixels
     */
    height?: number | null;
    /**
     * Duration in seconds (for videos)
     */
    duration?: number | null;
    /**
     * Number of pages (for PDFs)
     */
    pages?: number | null;
    /**
     * Which page of the PDF to use for thumbnails (changes will apply after saving)
     */
    selected_page?: number | null;
    /**
     * URL for the thumbnail image (automatically generated for PDFs)
     */
    thumbnail_url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses".
 */
export interface Course {
  id: number;
  title: string;
  slug: string;
  subtitle?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  excerpt?: string | null;
  featuredImage?: (number | null) | Media;
  type: 'frontal' | 'digital' | 'workshop' | 'coaching';
  /**
   * למשל: 12 שבועות
   */
  duration?: string | null;
  /**
   * למשל: ימי שני 17:00-21:00
   */
  schedule?: string | null;
  location?: string | null;
  hasZoom?: boolean | null;
  maxStudents?: number | null;
  /**
   * למשל: 3 מרצים על 18 תלמידים
   */
  instructorRatio?: string | null;
  certificate?: string | null;
  certificateDescription?: string | null;
  price?: number | null;
  showPrice?: boolean | null;
  /**
   * מחירון לקורסים עם מספר אופציות (פרונטלי, זום, וכו')
   */
  pricingTracks?:
    | {
        /**
         * לדוגמה: מסלול פרונטלי, מסלול Zoom
         */
        name: string;
        /**
         * לדוגמה: הרצליה פיתוח | ימי שישי | 9:00-12:00
         */
        schedule?: string | null;
        price: number;
        originalPrice?: number | null;
        /**
         * לדוגמה: מחיר השקה מוקדם
         */
        priceNote?: string | null;
        features?:
          | {
              text?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * לדוגמה: 27.02.2026
   */
  nextCohortDate?: string | null;
  /**
   * כרטיסי שיווק שמסבירים למה עכשיו זה הזמן להצטרף
   */
  whyNow?:
    | {
        icon?: string | null;
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  /**
   * תגים כמו "8 מפגשים", "קבוצות קטנות", וכו'
   */
  trustBadges?:
    | {
        icon?: string | null;
        text: string;
        id?: string | null;
      }[]
    | null;
  highlights?:
    | {
        /**
         * שם אייקון מ-Lucide
         */
        icon?: string | null;
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * תכנית הלימודים - מפגשים/שבועות
   */
  syllabus?:
    | {
        number: number;
        title: string;
        description: string;
        topics?:
          | {
              text?: string | null;
              id?: string | null;
            }[]
          | null;
        /**
         * כלי AI שילמדו במפגש (ChatGPT, Claude, וכו')
         */
        tools?:
          | {
              name?: string | null;
              id?: string | null;
            }[]
          | null;
        /**
         * אמוג'י או אייקון
         */
        icon?: string | null;
        id?: string | null;
      }[]
    | null;
  faq?:
    | {
        question: string;
        answer: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
      }[]
    | null;
  gallery?:
    | {
        image: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  instructors?: (number | Instructor)[] | null;
  testimonials?: (number | Testimonial)[] | null;
  ctaText?: string | null;
  ctaType?: ('contact' | 'purchase' | 'link') | null;
  ctaLink?: string | null;
  status?: ('draft' | 'published') | null;
  order?: number | null;
  featured?: boolean | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "instructors".
 */
export interface Instructor {
  id: number;
  name: string;
  slug?: string | null;
  title?: string | null;
  bio?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  shortBio?: string | null;
  image?: (number | null) | Media;
  /**
   * ישמש רק אם לא הועלתה תמונה
   */
  externalImageUrl?: string | null;
  email?: string | null;
  linkedin?: string | null;
  specialties?:
    | {
        specialty?: string | null;
        id?: string | null;
      }[]
    | null;
  order?: number | null;
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  name: string;
  role?: string | null;
  image?: (number | null) | Media;
  /**
   * ישמש רק אם לא הועלתה תמונה
   */
  externalImageUrl?: string | null;
  content: string;
  rating?: number | null;
  course?: (number | null) | Course;
  videoUrl?: string | null;
  featured?: boolean | null;
  status?: ('pending' | 'approved') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cohorts".
 */
export interface Cohort {
  id: number;
  title: string;
  slug?: string | null;
  course: number | Course;
  startDate: string;
  endDate?: string | null;
  schedule?: string | null;
  location?: string | null;
  zoomLink?: string | null;
  whatsappGroup?: string | null;
  maxStudents?: number | null;
  instructors?: (number | User)[] | null;
  status?: ('upcoming' | 'active' | 'completed') | null;
  registrationOpen?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lessons".
 */
export interface Lesson {
  id: number;
  title: string;
  slug?: string | null;
  cohort: number | Cohort;
  order: number;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  date?: string | null;
  video?: {
    type?: ('url' | 'upload') | null;
    url?: string | null;
    file?: (number | null) | Media;
    duration?: number | null;
  };
  materials?:
    | {
        title: string;
        file: number | Media;
        id?: string | null;
      }[]
    | null;
  status?: ('draft' | 'published') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enrollments".
 */
export interface Enrollment {
  id: number;
  student: number | User;
  cohort: number | Cohort;
  status?: ('pending' | 'active' | 'completed' | 'cancelled') | null;
  enrolledAt?: string | null;
  completedAt?: string | null;
  paymentStatus?: ('pending' | 'paid' | 'refunded') | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "progress".
 */
export interface Progress {
  id: number;
  student: number | User;
  lesson: number | Lesson;
  watched?: boolean | null;
  watchedAt?: string | null;
  watchTime?: number | null;
  completed?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "attendance".
 */
export interface Attendance {
  id: number;
  student: number | User;
  lesson: number | Lesson;
  cohort: number | Cohort;
  date: string;
  present?: boolean | null;
  joinedAt?: string | null;
  leftAt?: string | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "assignments".
 */
export interface Assignment {
  id: number;
  title: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  cohort: number | Cohort;
  type?: ('homework' | 'exam' | 'project') | null;
  dueDate?: string | null;
  attachments?:
    | {
        file: number | Media;
        id?: string | null;
      }[]
    | null;
  maxScore?: number | null;
  status?: ('draft' | 'published') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "submissions".
 */
export interface Submission {
  id: number;
  student: number | User;
  assignment: number | Assignment;
  files?:
    | {
        file: number | Media;
        id?: string | null;
      }[]
    | null;
  notes?: string | null;
  submittedAt?: string | null;
  score?: number | null;
  feedback?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  status?: ('pending' | 'graded' | 'returned') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "certificates".
 */
export interface Certificate {
  id: number;
  student: number | User;
  course: number | Course;
  cohort?: (number | null) | Cohort;
  certificateNumber?: string | null;
  issuedAt?: string | null;
  file?: (number | null) | Media;
  status?: ('pending' | 'issued' | 'revoked') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  slug: string;
  excerpt?: string | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  featuredImage?: (number | null) | Media;
  category?: (number | null) | Category;
  author?: (number | null) | User;
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  cta?: {
    enabled?: boolean | null;
    text?: string | null;
    url?: string | null;
    style?: ('primary' | 'secondary') | null;
  };
  relatedCourse?: (number | null) | Course;
  readTime?: number | null;
  status?: ('draft' | 'published') | null;
  publishedAt?: string | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  slug: string;
  description?: string | null;
  /**
   * קוד צבע HEX
   */
  color?: string | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contacts".
 */
export interface Contact {
  id: number;
  name: string;
  email: string;
  phone: string;
  company?: string | null;
  interest?: ('bot-camp' | 'ai-ready' | 'workshop' | 'coaching' | 'digital' | 'general') | null;
  message?: string | null;
  /**
   * מאיזה עמוד הגיע - נקבע אוטומטית
   */
  source?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners".
 */
export interface Partner {
  id: number;
  name: string;
  logo?: (number | null) | Media;
  /**
   * ישמש רק אם לא הועלה לוגו
   */
  externalLogoUrl?: string | null;
  website?: string | null;
  type: 'academic' | 'corporate' | 'media';
  featured?: boolean | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'courses';
        value: number | Course;
      } | null)
    | ({
        relationTo: 'cohorts';
        value: number | Cohort;
      } | null)
    | ({
        relationTo: 'lessons';
        value: number | Lesson;
      } | null)
    | ({
        relationTo: 'enrollments';
        value: number | Enrollment;
      } | null)
    | ({
        relationTo: 'progress';
        value: number | Progress;
      } | null)
    | ({
        relationTo: 'attendance';
        value: number | Attendance;
      } | null)
    | ({
        relationTo: 'assignments';
        value: number | Assignment;
      } | null)
    | ({
        relationTo: 'submissions';
        value: number | Submission;
      } | null)
    | ({
        relationTo: 'certificates';
        value: number | Certificate;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'instructors';
        value: number | Instructor;
      } | null)
    | ({
        relationTo: 'contacts';
        value: number | Contact;
      } | null)
    | ({
        relationTo: 'partners';
        value: number | Partner;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  phone?: T;
  avatar?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  category?: T;
  externalUrl?: T;
  cloudinary?:
    | T
    | {
        public_id?: T;
        resource_type?: T;
        format?: T;
        secure_url?: T;
        bytes?: T;
        created_at?: T;
        version?: T;
        version_id?: T;
        width?: T;
        height?: T;
        duration?: T;
        pages?: T;
        selected_page?: T;
        thumbnail_url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses_select".
 */
export interface CoursesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  subtitle?: T;
  description?: T;
  excerpt?: T;
  featuredImage?: T;
  type?: T;
  duration?: T;
  schedule?: T;
  location?: T;
  hasZoom?: T;
  maxStudents?: T;
  instructorRatio?: T;
  certificate?: T;
  certificateDescription?: T;
  price?: T;
  showPrice?: T;
  pricingTracks?:
    | T
    | {
        name?: T;
        schedule?: T;
        price?: T;
        originalPrice?: T;
        priceNote?: T;
        features?:
          | T
          | {
              text?: T;
              id?: T;
            };
        id?: T;
      };
  nextCohortDate?: T;
  whyNow?:
    | T
    | {
        icon?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  trustBadges?:
    | T
    | {
        icon?: T;
        text?: T;
        id?: T;
      };
  highlights?:
    | T
    | {
        icon?: T;
        text?: T;
        id?: T;
      };
  syllabus?:
    | T
    | {
        number?: T;
        title?: T;
        description?: T;
        topics?:
          | T
          | {
              text?: T;
              id?: T;
            };
        tools?:
          | T
          | {
              name?: T;
              id?: T;
            };
        icon?: T;
        id?: T;
      };
  faq?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  gallery?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  instructors?: T;
  testimonials?: T;
  ctaText?: T;
  ctaType?: T;
  ctaLink?: T;
  status?: T;
  order?: T;
  featured?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cohorts_select".
 */
export interface CohortsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  course?: T;
  startDate?: T;
  endDate?: T;
  schedule?: T;
  location?: T;
  zoomLink?: T;
  whatsappGroup?: T;
  maxStudents?: T;
  instructors?: T;
  status?: T;
  registrationOpen?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lessons_select".
 */
export interface LessonsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  cohort?: T;
  order?: T;
  description?: T;
  date?: T;
  video?:
    | T
    | {
        type?: T;
        url?: T;
        file?: T;
        duration?: T;
      };
  materials?:
    | T
    | {
        title?: T;
        file?: T;
        id?: T;
      };
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enrollments_select".
 */
export interface EnrollmentsSelect<T extends boolean = true> {
  student?: T;
  cohort?: T;
  status?: T;
  enrolledAt?: T;
  completedAt?: T;
  paymentStatus?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "progress_select".
 */
export interface ProgressSelect<T extends boolean = true> {
  student?: T;
  lesson?: T;
  watched?: T;
  watchedAt?: T;
  watchTime?: T;
  completed?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "attendance_select".
 */
export interface AttendanceSelect<T extends boolean = true> {
  student?: T;
  lesson?: T;
  cohort?: T;
  date?: T;
  present?: T;
  joinedAt?: T;
  leftAt?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "assignments_select".
 */
export interface AssignmentsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  cohort?: T;
  type?: T;
  dueDate?: T;
  attachments?:
    | T
    | {
        file?: T;
        id?: T;
      };
  maxScore?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "submissions_select".
 */
export interface SubmissionsSelect<T extends boolean = true> {
  student?: T;
  assignment?: T;
  files?:
    | T
    | {
        file?: T;
        id?: T;
      };
  notes?: T;
  submittedAt?: T;
  score?: T;
  feedback?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "certificates_select".
 */
export interface CertificatesSelect<T extends boolean = true> {
  student?: T;
  course?: T;
  cohort?: T;
  certificateNumber?: T;
  issuedAt?: T;
  file?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  content?: T;
  featuredImage?: T;
  category?: T;
  author?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  cta?:
    | T
    | {
        enabled?: T;
        text?: T;
        url?: T;
        style?: T;
      };
  relatedCourse?: T;
  readTime?: T;
  status?: T;
  publishedAt?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  color?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  image?: T;
  externalImageUrl?: T;
  content?: T;
  rating?: T;
  course?: T;
  videoUrl?: T;
  featured?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "instructors_select".
 */
export interface InstructorsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  title?: T;
  bio?: T;
  shortBio?: T;
  image?: T;
  externalImageUrl?: T;
  email?: T;
  linkedin?: T;
  specialties?:
    | T
    | {
        specialty?: T;
        id?: T;
      };
  order?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contacts_select".
 */
export interface ContactsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  company?: T;
  interest?: T;
  message?: T;
  source?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners_select".
 */
export interface PartnersSelect<T extends boolean = true> {
  name?: T;
  logo?: T;
  externalLogoUrl?: T;
  website?: T;
  type?: T;
  featured?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName?: string | null;
  siteDescription?: string | null;
  logo?: (number | null) | Media;
  favicon?: (number | null) | Media;
  contact?: {
    email?: string | null;
    phone?: string | null;
    whatsapp?: string | null;
    address?: string | null;
  };
  social?: {
    facebook?: string | null;
    instagram?: string | null;
    linkedin?: string | null;
    youtube?: string | null;
    tiktok?: string | null;
  };
  tracking?: {
    metaPixel?: string | null;
    tiktokPixel?: string | null;
    googleAnalytics?: string | null;
    fixdigitalClientKey?: string | null;
  };
  /**
   * הוספת קודי מעקב וסקריפטים חיצוניים לאתר
   */
  scripts?: {
    /**
     * קוד שירוץ בתוך תגית <head>
     */
    headScripts?: string | null;
    /**
     * קוד שירוץ מיד אחרי <body>
     */
    bodyStartScripts?: string | null;
    /**
     * קוד שירוץ לפני </body>
     */
    footerScripts?: string | null;
  };
  /**
   * ניהול פיקסלים בצורה מובנית
   */
  pixels?:
    | {
        platform: 'meta' | 'tiktok' | 'google' | 'googleAds' | 'linkedin' | 'twitter' | 'fixdigital' | 'custom';
        pixelId: string;
        enabled?: boolean | null;
        customScript?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  mainMenu?:
    | {
        label?: string | null;
        url?: string | null;
        openInNewTab?: boolean | null;
        children?:
          | {
              label?: string | null;
              url?: string | null;
              openInNewTab?: boolean | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  footerMenu?:
    | {
        label?: string | null;
        url?: string | null;
        openInNewTab?: boolean | null;
        id?: string | null;
      }[]
    | null;
  ctaButton?: {
    text?: string | null;
    url?: string | null;
    isVisible?: boolean | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * כל התוכן של דף הבית - כותרות, סטטיסטיקות, CTAs
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: number;
  /**
   * הסקשן הראשי בראש הדף
   */
  hero?: {
    title?: string | null;
    /**
     * המילה שתהיה בצבע הגרדיאנט
     */
    titleHighlight?: string | null;
    subtitle?: string | null;
    image?: (number | null) | Media;
    primaryCta?: {
      text?: string | null;
      link?: string | null;
    };
    secondaryCta?: {
      text?: string | null;
      link?: string | null;
    };
  };
  /**
   * מספרים שמוצגים בכל האתר (דף הבית, אודות וכו')
   */
  globalStats: {
    graduates: {
      value: number;
      label?: string | null;
      suffix?: string | null;
    };
    courses: {
      value: number;
      label?: string | null;
      suffix?: string | null;
    };
    companies: {
      value: number;
      label?: string | null;
      suffix?: string | null;
    };
    satisfaction: {
      value: number;
      label?: string | null;
      suffix?: string | null;
    };
  };
  /**
   * שדה ישן - השתמש ב-globalStats במקום
   */
  stats?:
    | {
        number?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * נקודות מפתח שמסבירות למה לבחור בנו
   */
  whyUs?:
    | {
        icon?: string | null;
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  /**
   * סקשן אודות בדף הבית
   */
  about?: {
    title?: string | null;
    subtitle?: string | null;
    content?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    image?: (number | null) | Media;
    /**
     * נקודות מפתח שמוצגות בסקשן
     */
    features?:
      | {
          icon?: string | null;
          title: string;
          description?: string | null;
          id?: string | null;
        }[]
      | null;
    cta?: {
      text?: string | null;
      link?: string | null;
    };
  };
  /**
   * כותרות ותתי-כותרות לכל סקשן בדף
   */
  sections?: {
    programs?: {
      title?: string | null;
      subtitle?: string | null;
    };
    testimonials?: {
      title?: string | null;
      subtitle?: string | null;
    };
    team?: {
      title?: string | null;
      subtitle?: string | null;
    };
    partners?: {
      title?: string | null;
      subtitle?: string | null;
    };
    coursesTitle?: string | null;
    blogTitle?: string | null;
    testimonialsTitle?: string | null;
    partnersTitle?: string | null;
  };
  newsletter?: {
    title?: string | null;
    description?: string | null;
    buttonText?: string | null;
    webhookUrl?: string | null;
  };
  bottomCta?: {
    title?: string | null;
    subtitle?: string | null;
    showForm?: boolean | null;
    showWhatsapp?: boolean | null;
    primaryButton?: {
      text?: string | null;
      link?: string | null;
    };
    secondaryButton?: {
      text?: string | null;
      link?: string | null;
    };
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * תוכן דינמי לכל הדפים באתר
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  about?: {
    hero?: {
      title?: string | null;
      titleHighlight?: string | null;
      subtitle?: string | null;
    };
    mission?: {
      badge?: string | null;
      title?: string | null;
      titleHighlight?: string | null;
      paragraphs?:
        | {
            text: string;
            id?: string | null;
          }[]
        | null;
    };
    values?:
      | {
          icon?: string | null;
          title: string;
          description: string;
          id?: string | null;
        }[]
      | null;
    team?: {
      badge?: string | null;
      title?: string | null;
      subtitle?: string | null;
    };
    cta?: {
      title?: string | null;
      subtitle?: string | null;
      primaryButton?: {
        text?: string | null;
        link?: string | null;
      };
      secondaryButton?: {
        text?: string | null;
        link?: string | null;
      };
    };
  };
  courses?: {
    hero?: {
      title?: string | null;
      titleHighlight?: string | null;
      subtitle?: string | null;
    };
    emptyState?: {
      title?: string | null;
      subtitle?: string | null;
      buttonText?: string | null;
    };
    cta?: {
      title?: string | null;
      subtitle?: string | null;
      primaryButton?: {
        text?: string | null;
        link?: string | null;
      };
      secondaryButton?: {
        text?: string | null;
        link?: string | null;
      };
    };
  };
  blog?: {
    hero?: {
      title?: string | null;
      titleHighlight?: string | null;
      subtitle?: string | null;
    };
    emptyState?: {
      noResults?: string | null;
      noPosts?: string | null;
      noPostsSubtitle?: string | null;
      filterSubtitle?: string | null;
    };
    cta?: {
      title?: string | null;
      subtitle?: string | null;
      primaryButton?: {
        text?: string | null;
        link?: string | null;
      };
      secondaryButton?: {
        text?: string | null;
        link?: string | null;
      };
    };
    postCta?: {
      title?: string | null;
      subtitle?: string | null;
    };
  };
  thankYou?: {
    icon?: string | null;
    title?: string | null;
    subtitle?: string | null;
    description?: string | null;
    whatNext?: {
      title?: string | null;
      items?:
        | {
            icon?: string | null;
            text: string;
            id?: string | null;
          }[]
        | null;
    };
    buttons?:
      | {
          text: string;
          link: string;
          style?: ('primary' | 'secondary' | 'whatsapp') | null;
          icon?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * תוכן לדף הנחיתה AI Ready
   */
  aiReady?: {
    hero?: {
      badge?: string | null;
      title?: string | null;
      titleHighlight?: string | null;
      subtitle?: string | null;
      primaryCta?: string | null;
      secondaryCta?: string | null;
    };
    trustBadges?:
      | {
          icon?: string | null;
          text: string;
          id?: string | null;
        }[]
      | null;
    audience?: {
      title?: string | null;
      subtitle?: string | null;
    };
    benefits?: {
      title?: string | null;
      subtitle?: string | null;
    };
    pricing?: {
      title?: string | null;
      subtitle?: string | null;
      nextCohortDate?: string | null;
      frontalTrack?: {
        title?: string | null;
        schedule?: string | null;
        originalPrice?: string | null;
        price?: string | null;
        priceNote?: string | null;
      };
      zoomTrack?: {
        title?: string | null;
        schedule?: string | null;
        originalPrice?: string | null;
        price?: string | null;
        priceNote?: string | null;
      };
    };
    testimonials?: {
      badge?: string | null;
      title?: string | null;
      titleHighlight?: string | null;
    };
    about?: {
      title?: string | null;
    };
    team?: {
      title?: string | null;
      subtitle?: string | null;
    };
    cta?: {
      title?: string | null;
      subtitle?: string | null;
    };
    form?: {
      title?: string | null;
      subtitle?: string | null;
      buttonText?: string | null;
    };
  };
  /**
   * טקסטים וכותרות לדפי קורסים בודדים
   */
  courseSingle?: {
    buttons?: {
      register?: string | null;
      syllabus?: string | null;
      contact?: string | null;
      backHome?: string | null;
    };
    sections?: {
      whoIsItFor?: string | null;
      whyNow?: string | null;
      whatYouGet?: string | null;
      highlights?: string | null;
      syllabus?: string | null;
      team?: string | null;
      testimonials?: string | null;
      faq?: string | null;
    };
    alerts?: {
      spotsLeft?: string | null;
    };
    cta?: {
      title?: string | null;
      subtitle?: string | null;
    };
  };
  /**
   * הגדרות ברירת מחדל ל-CTA sections בכל הדפים
   */
  commonCta?: {
    whatsappNumber?: string | null;
    whatsappText?: string | null;
    contactButtonText?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  siteDescription?: T;
  logo?: T;
  favicon?: T;
  contact?:
    | T
    | {
        email?: T;
        phone?: T;
        whatsapp?: T;
        address?: T;
      };
  social?:
    | T
    | {
        facebook?: T;
        instagram?: T;
        linkedin?: T;
        youtube?: T;
        tiktok?: T;
      };
  tracking?:
    | T
    | {
        metaPixel?: T;
        tiktokPixel?: T;
        googleAnalytics?: T;
        fixdigitalClientKey?: T;
      };
  scripts?:
    | T
    | {
        headScripts?: T;
        bodyStartScripts?: T;
        footerScripts?: T;
      };
  pixels?:
    | T
    | {
        platform?: T;
        pixelId?: T;
        enabled?: T;
        customScript?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  mainMenu?:
    | T
    | {
        label?: T;
        url?: T;
        openInNewTab?: T;
        children?:
          | T
          | {
              label?: T;
              url?: T;
              openInNewTab?: T;
              id?: T;
            };
        id?: T;
      };
  footerMenu?:
    | T
    | {
        label?: T;
        url?: T;
        openInNewTab?: T;
        id?: T;
      };
  ctaButton?:
    | T
    | {
        text?: T;
        url?: T;
        isVisible?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        title?: T;
        titleHighlight?: T;
        subtitle?: T;
        image?: T;
        primaryCta?:
          | T
          | {
              text?: T;
              link?: T;
            };
        secondaryCta?:
          | T
          | {
              text?: T;
              link?: T;
            };
      };
  globalStats?:
    | T
    | {
        graduates?:
          | T
          | {
              value?: T;
              label?: T;
              suffix?: T;
            };
        courses?:
          | T
          | {
              value?: T;
              label?: T;
              suffix?: T;
            };
        companies?:
          | T
          | {
              value?: T;
              label?: T;
              suffix?: T;
            };
        satisfaction?:
          | T
          | {
              value?: T;
              label?: T;
              suffix?: T;
            };
      };
  stats?:
    | T
    | {
        number?: T;
        label?: T;
        id?: T;
      };
  whyUs?:
    | T
    | {
        icon?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  about?:
    | T
    | {
        title?: T;
        subtitle?: T;
        content?: T;
        image?: T;
        features?:
          | T
          | {
              icon?: T;
              title?: T;
              description?: T;
              id?: T;
            };
        cta?:
          | T
          | {
              text?: T;
              link?: T;
            };
      };
  sections?:
    | T
    | {
        programs?:
          | T
          | {
              title?: T;
              subtitle?: T;
            };
        testimonials?:
          | T
          | {
              title?: T;
              subtitle?: T;
            };
        team?:
          | T
          | {
              title?: T;
              subtitle?: T;
            };
        partners?:
          | T
          | {
              title?: T;
              subtitle?: T;
            };
        coursesTitle?: T;
        blogTitle?: T;
        testimonialsTitle?: T;
        partnersTitle?: T;
      };
  newsletter?:
    | T
    | {
        title?: T;
        description?: T;
        buttonText?: T;
        webhookUrl?: T;
      };
  bottomCta?:
    | T
    | {
        title?: T;
        subtitle?: T;
        showForm?: T;
        showWhatsapp?: T;
        primaryButton?:
          | T
          | {
              text?: T;
              link?: T;
            };
        secondaryButton?:
          | T
          | {
              text?: T;
              link?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  about?:
    | T
    | {
        hero?:
          | T
          | {
              title?: T;
              titleHighlight?: T;
              subtitle?: T;
            };
        mission?:
          | T
          | {
              badge?: T;
              title?: T;
              titleHighlight?: T;
              paragraphs?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
            };
        values?:
          | T
          | {
              icon?: T;
              title?: T;
              description?: T;
              id?: T;
            };
        team?:
          | T
          | {
              badge?: T;
              title?: T;
              subtitle?: T;
            };
        cta?:
          | T
          | {
              title?: T;
              subtitle?: T;
              primaryButton?:
                | T
                | {
                    text?: T;
                    link?: T;
                  };
              secondaryButton?:
                | T
                | {
                    text?: T;
                    link?: T;
                  };
            };
      };
  courses?:
    | T
    | {
        hero?:
          | T
          | {
              title?: T;
              titleHighlight?: T;
              subtitle?: T;
            };
        emptyState?:
          | T
          | {
              title?: T;
              subtitle?: T;
              buttonText?: T;
            };
        cta?:
          | T
          | {
              title?: T;
              subtitle?: T;
              primaryButton?:
                | T
                | {
                    text?: T;
                    link?: T;
                  };
              secondaryButton?:
                | T
                | {
                    text?: T;
                    link?: T;
                  };
            };
      };
  blog?:
    | T
    | {
        hero?:
          | T
          | {
              title?: T;
              titleHighlight?: T;
              subtitle?: T;
            };
        emptyState?:
          | T
          | {
              noResults?: T;
              noPosts?: T;
              noPostsSubtitle?: T;
              filterSubtitle?: T;
            };
        cta?:
          | T
          | {
              title?: T;
              subtitle?: T;
              primaryButton?:
                | T
                | {
                    text?: T;
                    link?: T;
                  };
              secondaryButton?:
                | T
                | {
                    text?: T;
                    link?: T;
                  };
            };
        postCta?:
          | T
          | {
              title?: T;
              subtitle?: T;
            };
      };
  thankYou?:
    | T
    | {
        icon?: T;
        title?: T;
        subtitle?: T;
        description?: T;
        whatNext?:
          | T
          | {
              title?: T;
              items?:
                | T
                | {
                    icon?: T;
                    text?: T;
                    id?: T;
                  };
            };
        buttons?:
          | T
          | {
              text?: T;
              link?: T;
              style?: T;
              icon?: T;
              id?: T;
            };
      };
  aiReady?:
    | T
    | {
        hero?:
          | T
          | {
              badge?: T;
              title?: T;
              titleHighlight?: T;
              subtitle?: T;
              primaryCta?: T;
              secondaryCta?: T;
            };
        trustBadges?:
          | T
          | {
              icon?: T;
              text?: T;
              id?: T;
            };
        audience?:
          | T
          | {
              title?: T;
              subtitle?: T;
            };
        benefits?:
          | T
          | {
              title?: T;
              subtitle?: T;
            };
        pricing?:
          | T
          | {
              title?: T;
              subtitle?: T;
              nextCohortDate?: T;
              frontalTrack?:
                | T
                | {
                    title?: T;
                    schedule?: T;
                    originalPrice?: T;
                    price?: T;
                    priceNote?: T;
                  };
              zoomTrack?:
                | T
                | {
                    title?: T;
                    schedule?: T;
                    originalPrice?: T;
                    price?: T;
                    priceNote?: T;
                  };
            };
        testimonials?:
          | T
          | {
              badge?: T;
              title?: T;
              titleHighlight?: T;
            };
        about?:
          | T
          | {
              title?: T;
            };
        team?:
          | T
          | {
              title?: T;
              subtitle?: T;
            };
        cta?:
          | T
          | {
              title?: T;
              subtitle?: T;
            };
        form?:
          | T
          | {
              title?: T;
              subtitle?: T;
              buttonText?: T;
            };
      };
  courseSingle?:
    | T
    | {
        buttons?:
          | T
          | {
              register?: T;
              syllabus?: T;
              contact?: T;
              backHome?: T;
            };
        sections?:
          | T
          | {
              whoIsItFor?: T;
              whyNow?: T;
              whatYouGet?: T;
              highlights?: T;
              syllabus?: T;
              team?: T;
              testimonials?: T;
              faq?: T;
            };
        alerts?:
          | T
          | {
              spotsLeft?: T;
            };
        cta?:
          | T
          | {
              title?: T;
              subtitle?: T;
            };
      };
  commonCta?:
    | T
    | {
        whatsappNumber?: T;
        whatsappText?: T;
        contactButtonText?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}